---

- name: disable Apache service
  systemd:
    name: apache2
    enabled: false

- name: Make sure Apache service is stopped
  systemd:
    state: stopped
    name: apache2


- name: disable MariaDB service
  systemd:
    name: mariadb
    enabled: false

- name: Make sure MariaDB service is stopped
  systemd:
    state: stopped
    name: mariadb


- name: remove Apache package
  apt:
    name: apache2
    state: absent
    purge: yes
    force: yes

- name: remove MariaDb package
  apt:
    name: mariadb-server
    state: absent
    purge: yes
    force: yes

- name: remove MariaDb package
  apt:
    name: mariadb-client
    state: absent
    purge: yes
    force: yes

- name: remove MariaDb package
  apt:
    name: mariadb-common
    state: absent
    purge: yes
    force: yes


- name: main | uninstall php packages
  apt: >
    pkg={{ item }} 
    state=absent
    purge=yes
    force=yes
  with_items:
    - php*


- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: removing firewalld rules for http
  firewalld:
    service: http
    permanent: true
    state: disabled

- name: removing firewalld rules for https 
  firewalld:
    service: https
    permanent: true
    state: disabled
  notify: Reloading firewalld rules
